name: manual

on:
  workflow_dispatch:

env:
  FLAG: ${{ secrets.FLAG }}

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.12
