name: manual

on:
  workflow_dispatch:

env:
  FLAG: ${{ secrets.FLAG }}

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - run: npm i
      - run: npm run
      - run: ls -la ../../../.npm/
    
